version: "3"
services:
  mycloudcore:
    build: .
    image: mycloudcore:latest
    container_name: my-cloud-core
    pull_policy: build
    ports:
      - "8099:5000"
    volumes:
      - ./channels.json:/app/channels.json
    restart: always